name: Create Release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Create ZIP archive
        run: |
          zip -r Geensnor.zip Geensnor
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: Geensnor.zip
